name: ramzino
description: store all password in one place

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil:
  flutter_spinkit:
  dots_indicator:
  flutter_bloc:
  shared_preferences:
  local_auth: ^2.1.7
  dartz: ^0.10.1
  equatable:
  fluttertoast:
  get_it: ^7.6.4
  flutter_secure_storage: ^9.0.0
  json_annotation:
  hive: ^2.2.3
  hive_flutter:
  uuid: ^4.2.1
  flutter_animate: ^4.3.0
  

dev_dependencies:
  json_serializable:
  hive_generator:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/img/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: yekan
      fonts:
        - asset: assets/fonts/B Yekan_YasDL.com.ttf
    - family: Amaranth
      fonts:
        - asset: assets/fonts/Amaranth-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
